version: 2
updates:
  - package-ecosystem: maven
    directory: app
    schedule:
      interval: daily
    target-branch: dev

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: dev